import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/page";
import { sideMenu } from "./components/sidebar/sideMenu";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="inline-flex w-full">

          {/* <Sidebar menus={sideMenu}/> */}
          <Sidebar />
          <div className="flex flex-col sm:gap-4 sm:pt-4 sm:pl-10 sm:pr-5 w-full h-full items-center">
            {children}
          </div>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
