import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/page";
import { sideMenu } from "./components/sidebar/sideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="flex w-full min-h-screen max-h-screen">
  
            <Sidebar menus={sideMenu}/>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
